# Generated by Django 5.2.7 on 2026-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер заказ-наряда')),
                ('equipment', models.CharField(max_length=45, verbose_name='Наименование')),
                ('plc_name', models.CharField(max_length=15, verbose_name='ПЛК')),
                ('hmi_name', models.CharField(max_length=15, verbose_name='Панель')),
                ('regul_name', models.CharField(max_length=15, verbose_name='Наименование')),
                ('date', models.DateField(verbose_name='Дата получения заказа')),
                ('status', models.CharField(choices=[('work', 'В работе'), ('not_run', 'Выполнен, но не запущен'), ('done', 'Выполнен, но не запущен')], default='work', max_length=15, verbose_name='Статус')),
                ('pid_regul', models.CharField(max_length=15, verbose_name='ПИД регулятор')),
                ('scada', models.CharField(max_length=15, verbose_name='SCADA')),
                ('opc', models.CharField(max_length=15, verbose_name='OPC')),
                ('comments', models.TextField(max_length=250, verbose_name='Комментарий')),
                ('status_rom', models.CharField(choices=[('NOT', 'Не сделаны'), ('YES', 'Сделаны')], default='NOT', max_length=15, verbose_name='Статус заявок')),
                ('date_rom', models.DateField(verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заказы',
                'ordering': ['number', 'date'],
            },
        ),
    ]
